apiVersion: v1
kind: Service
metadata:
  name: node-concepts

spec:
  selector:
    app: node-concepts
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-concepts
  labels:
    app: node-concepts

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: node-concepts
  template:
    metadata:
      labels:
        app: node-concepts
    spec:
      containers:
        - name: node-concepts
          image: node-concepts
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 15
            timeoutSeconds: 30
          imagePullPolicy: IfNotPresent
      serviceAccountName: default

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-concepts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-concepts
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 75m
